input_data_path: "data/raw/heart.csv"
input_model_path: "models/model.pkl"
output_data_path: "data/preds/heart_preds.csv"
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
