input_data_path: "data/raw/heart.csv"
output_model_path: "models/model.pkl"
metric_path: "models/metrics.json"
split_params:
  val_size: 0.2
  random_state: 42
model_params:
  model_type: "RandomForestClassifier"
  n_estimators: 200
  random_state: 42
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  age_threshold: 40
  target_col: "target"
